### ISSUE TITLE
[vite-node] [ERR_INVALID_URL_SCHEME] /@fs

### ISSUE THREAD

**Issue by danielduckworth** [productdevbook/productdevbook.com#66]
Hi, I used this template, installed with yarn but when I try to run in dev mode I get this error:

[vite-node] [ERR_INVALID_URL_SCHEME] /@fs/G:/Code/03 Projects/00 Experimental/oku-nuxt3/.nuxt/i18n.options.mjs

If I build for production and server it works.

Any ideas on how to fix the dev mode?

**Comment by productdevbook** [comment]
this is https://github.com/productdevbook/oku-nuxt3-template ? template, 

I think you opened issua in the wrong place.
